# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "PR Build"

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: Build 
    runs-on: windows-2022
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET build dependencies
      uses: timheuer/bootstrap-dotnet@v1

    - name: Increment VSIX version
      id: vsix_version
      uses: ./.github/workflows/composite/vsixversion
      with:
        manifest-file: src\RestClientVS\source.extension.vsixmanifest
        vsix-token-source-file: src\RestClientVS\source.extension.cs

    - name: Restore
      run: nuget restore -Verbosity quiet

    - name: Build
      run: msbuild src\RestClientVS\RestClientVS.csproj /p:Configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m /p:OutDir=../../built

    - name: Test
      run: dotnet test test/RestClientTest/RestClientTest.csproj

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: RestClientVS.vsix
        path: built/**/*.vsix