# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "PR Build"

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: Build 
    runs-on: windows-2022
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      VSIX_VERSION: 1.0.${{ github.run_number }}
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Set version for Visual Studio Extension
      uses: cezarypiatek/VsixVersionAction@1.0
      with:
        version: ${{ env.VSIX_VERSION }}
        vsix-manifest-file: src\RestClientVS\source.extension.vsixmanifest

    - name: VSIX token replacement
      shell: pwsh
      run: |
        $filePath = "src\RestClientVS\source.extension.cs"
        $replacement = 'Version = "${{ env.VSIX_VERSION }}"'
        $content = [string]::join([environment]::newline, (get-content $filePath))
        $regex = New-Object System.Text.RegularExpressions.Regex 'Version = "([0-9\\.]+)"'
        $regex.Replace($content, $replacement) | Out-File $FilePath

    - name: Restore
      run: nuget restore -Verbosity quiet

    - name: Build
      run: msbuild src\RestClientVS\RestClientVS.csproj /p:Configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m /p:OutDir=../../built

    - name: Test
      run: dotnet test test/RestClientTest/RestClientTest.csproj

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: RestClientVS.vsix
        path: built/**/*.vsix